version: "3"
services:

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: project
      MYSQL_ROOT_PASSWORD : dbdb7283
    ports:
      - 3308:3306
    volumes:
      - ./docker/data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis
    ports:
      - 6359:6379
    volumes:
      - ./docker/data:/var/lib/redis

  springbootapp:
    build: .
    container_name: springbootapp
    ports:
      - 80:8080
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/app/
