server:
  servlet:
    encoding:
      force: 'true'
      enabled: 'true'
      charset: UTF-8
  port: '8080'
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
    org:
      springframework:
        transaction: error
spring:
  config:
    import:
    - classpath:application-db.yml
    - classpath:application-jwt.yml
    - classpath:application-local.yml
    - classpath:application-s3.yml
  servlet:
    multipart:
      max-file-size: 50MB
      enabled: 'true'
      max-request-size: 50MB
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: 'true'
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(6NFu+m2WQ5FGKHTKFcEOk+E2/XswsFG6pCkY4H1WRkc=)
    password: ENC(IcSnydQfBYwUFAJK25xwcwlbPEqBR97VMtNfZI0WWCM=)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

lombok:
  anyConstructor:
    addConstructorProperties: 'true'
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: 1234
