spring:
  datasource:
    username: ENC(AT1nIJMxDvl0ImnKwFf5KQ==)
    url: ENC(WNnI13S3CPApSryu0wwUBYLK3/Q0/faaWINcbiYlncMIB4b3z86EkWO50W3ZQ4lYL1+AA4pwGAB31hBNF1DOpRrprH4dSD5CF34qih7EVMHLHgkVR4YBclyWEe8Baz9SzJPoCDvbH9DW3l0ubsSktrBQqjGDqWNYYZyx9PCe/2mdQFHssV0gtag0vRklMS5YsNXYDLSHVUNZLOM/V40/y6qoKEFdM/S2GGdLpqyJWkugLRmmX7BZWQ==)
    password: ENC(62IrokPo8derpGOfHxzppjEc8y574JLJ)
  redis:
    host: redis.itbine.ng.0001.apn2.cache.amazonaws.com
    port: '6379'
