cloud:
  aws:
    credentials:
      access-key: ENC(VUvWk7Zfba5uWyEeXplQ+c5AerujSB1EGkKhtS3Lf9A=)
      secret-key: ENC(3T6Y4GSTwpWmJzBlLUMi6PaH4pUtneNI1bLBsdMUvzlRTWKYao8by77nYs9J0U0Z2zhMLYdJ8d8=)
    s3:
      bucket: fresh-pace-image
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'
